# Generated by Django 2.2 on 2022-02-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieticket', '0002_auto_20220209_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movie_title',
            new_name='project_title',
        ),
    ]
