# Generated by Django 4.0.2 on 2022-02-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieticket', '0003_auto_20220209_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
